#!/bin/bash -ex

# start xvfb
export DISPLAY=:99.0
sh -e /etc/init.d/xvfb start

# Set up ChromeDriver (required for Chrome & selenium)
wget --no-verbose --output-document chromedriver.zip "https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip"
unzip chromedriver.zip

# Set up Selenium
wget --no-verbose --output-document selenium.jar "https://selenium-release.storage.googleapis.com/3.7/selenium-server-standalone-3.7.0.jar"
java -Dwebdriver.chrome.driver=./chromedriver -jar selenium.jar > /dev/null &
